FROM ubuntu:14.04
MAINTAINER Jisto Inc. <support@jisto.com>

RUN apt-get update

RUN apt-get install -y software-properties-common \
                       python-software-properties \
                       time \
                       vim \
                       git \
                       tmux \
                       curl \
                       iptables

RUN apt-get clean
