FROM jisto-base-ubuntu1404
MAINTAINER Jisto Inc. <support@jisto.com>

RUN curl https://omnitruck.chef.io/install.sh | sudo bash -s -- -P chefdk -c stable -v 0.16.28                          

RUN apt-get clean
